[package]
name = "scheduling"
version = "0.1.0"
authors = ["Fergus Molloy <fdm504@york.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored="2"
env_logger = "0.8.2"
log = "0.4.13"
structopt = "0.3.21"
